---
name: "geodash"
version: "0.0.1"
description: "geodash 0.0.1"
path:
  geodash: "./src/geodash"
plugins:
  - { version: master, url: https://github.com/geodashio/geodash-plugin-base.git }
  - { version: master, url: https://github.com/geodashio/geodash-plugin-handlers.git }
  - { branch: master, url: https://github.com/geodashio/geodash-plugin-filters.git }
  #- file:///home/vagrant/geodash-plugin-filters.git
  - { branch: master, url: https://github.com/geodashio/geodash-plugin-legend.git }
  #- file:///home/vagrant/geodash-plugin-legend.git
  - welcome
  - about
  - download
  - { version: master, url: https://github.com/geodashio/geodash-plugin-overlays.git }
  #- file:///home/vagrant/geodash-plugin-overlays.git
  - { version: master, url: https://github.com/geodashio/geodash-plugin-navbars.git }
  #- file:///home/vagrant/geodash-plugin-navbars.git
  - sidebar_toggle_left
  - sidebar_toggle_right
resources:
  - name: jquery-ui.min.css
    path: ./lib/jquery-ui/1.11.4/jquery-ui.min.css
  - name: select2.min.css
    path: ./lib/select2/select2-4.0.1/dist/css/select2.min.css
  - name: select2-bootstrap.min.css
    path: ./lib/select2-bootstrap-theme/dist/select2-bootstrap.min.css
  - name: typeaheadjs.css
    path: ./lib/typeahead.js-bootstrap-css/typeaheadjs.css
  - name: c3.min.css
    path: "./lib/c3/0.4.10/c3.min.css"
  - name: leaflet.css
    path: ./lib/leaflet/1.0.0-b1/leaflet.css
  - name: leaflet.label.css
    path: ./lib/Leaflet.label/leaflet-master/leaflet.label.css
  - name: ol3.css
    path: "./lib/ol3/{{ version }}/ol.css"
  - name: font-awesome.min.css
    path: ./lib/font-awesome/4.5.0/css/font-awesome.min.
  # For development, comment the following.
  - name: geodash.js
    path: "./lib/geodashjs/{{ version }}/geodash.js"
    minified: "./lib/geodashjs/{{ version }}/geodash.min.js"
  # For development, uncomment the following
  #- name: geodash.js
  #  path: "/home/vagrant/geodash.js.git/dist/geodash.js"
  #  minified: "/home/vagrant/geodash.js.git/dist/geodash.min.js"
  - name: angular.js
    path: "./lib/angularjs/{{ version }}/angular.js"
    minified: "./lib/angularjs/{{ version }}/angular.min.js"
  - name: angular-route.js
    path: "./lib/angularjs/{{ version }}/angular-route.js"
    minified: "./lib/angularjs/{{ version }}/angular-route.min.js"
  - name: angular-sanitize.js
    path: "./lib/angularjs/{{ version }}/angular-sanitize.js"
    minified: "./lib/angularjs/{{ version }}/angular-sanitize.min.js"
  - name: angular-cookies.js
    path: "./lib/angularjs/{{ version }}/angular-cookies.js"
    minified: "./lib/angularjs/{{ version }}/angular-cookies.min.js"
  - name: jquery.js
    path: "./lib/jquery/{{ version }}/jquery-{{ version }}.js"
    minified: "./lib/jquery/{{ version }}/jquery-{{ version }}.min.js"
  - name: jquery-ui.js
    path: "./lib/jquery-ui/{{ version }}/jquery-ui.js"
    minified: "./lib/jquery-ui/{{ version }}/jquery-ui.min.js"
  - name: yaml.js
    path: "./lib/yamljs/develop/dist/yaml.js"
    minified: "./lib/yamljs/develop/dist/yaml.min.js"
  - name: select2.full.js
    path: "./lib/select2/select2-{{ version }}/dist/js/select2.full.js"
    minified: "./lib/select2/select2-{{ version }}/dist/js/select2.full.min.js"
  - name: typeahead.js
    path: "./lib/typeahead/{{ version }}/typeahead.bundle.js"
    minified: "./lib/typeahead/{{ version }}/typeahead.bundle.min.js"
  - name: bootstrap.js
    path: "./lib/bootstrap/{{ version }}/dist/js/bootstrap.js"
    minified: "./lib/bootstrap/{{ version }}/dist/js/bootstrap.min.js"
  - name: d3.js
    path: "./lib/d3/{{ version }}/d3.js"
    minified: "./lib/d3/{{ version }}/d3.min.js"
  - name: c3.js
    path: "./lib/c3/{{ version }}/c3.js"
    minified: "./lib/c3/{{ version }}/c3.min.js"
  - name: ol3.js
    path: "./lib/ol3/{{ version }}/ol-debug.js"
    minified: "./lib/ol3/{{ version }}/ol.js"
  - name: leaflet-src.js
    path: "./lib/leaflet/{{ version }}/leaflet-src.js"
    minified: "./lib/leaflet/{{ version }}/leaflet.js"
  - name: leaflet.utfgrid-src.js
    path: "./lib/Leaflet.utfgrid/dist/leaflet.utfgrid-src.js"
    minified: "./lib/Leaflet.utfgrid/dist/leaflet.utfgrid.js"
  - name: wfp-simpleheat.js
    path: "./lib/Leaflet.heat/custom/wfp-simpleheat.js"
  - name: wfp-heatcanvas.js
    path: "./lib/Leaflet.heat/custom/wfp-heatcanvas.js"
  - name: wfp-heatlayer.js
    path: "./lib/Leaflet.heat/custom/wfp-heatlayer.js"
  - name: leaflet.label-src.js
    path: "./lib/Leaflet.label/leaflet-master/leaflet.label-src.js"
    minified: "./lib/Leaflet.label/leaflet-master/leaflet.label.js"
  - name: leaflet.TileLayer.WMTS.js
    path: "./lib/leaflet.TileLayer.WMTS/{{ version }}/leaflet-tilelayer-wmts-src.js"
    minified: "./lib/leaflet.TileLayer.WMTS/{{ version }}/leaflet-tilelayer-wmts.js"
  - name: showdown.js
    path: "./lib/showdown/{{ version }}/showdown.js"
    minified: "./lib/showdown/{{ version }}/showdown.min.js"
